### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by waltoncade** [SDSURocketProject/FAR-MARS#14] opened 2019-02-12 21:43 UTC
After long run times, the log file "overflows"? After trying to start the program again, 'Segmentation Fault' appears and program does not run. After restarting raspberry pi and PCB, Segmentation Fault still appears. Only after deleting log file on raspberry pi, does the program run normally again.

**Comment by alefir** [comment] 2019-02-12 23:07
what do you mean by "log file overflows"

is the time it takes for this to happen consistent?

**Comment by waltoncade** [comment] 2019-02-13 07:32
It only happened once. But i figured it had something to do with the log file, because when I deleted it, the problem stopped happening.

**Comment by alefir** [comment] 2019-03-29 07:09
closing because error could not be reproduced

**Closed by alefir** 2019-03-29 07:09 UTC
